/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddCustomForm.java
 *
 * Created on Nov 10, 2009, 9:32:03 AM
 */

package GUI;

import Business.CustomerManage;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class AddCustomForm extends javax.swing.JDialog {

    /** Creates new form AddCustomForm */
    public AddCustomForm(java.awt.Frame parent, boolean modal,String type) {
        super(parent, modal);
        initComponents();
        custMn = new CustomerManage();
        cbxCustTypeModel = new DefaultComboBoxModel(new String[] {"Customer","Dealer","Retailer"});
        cbxCustType.setModel(cbxCustTypeModel);
        cbxCustType.setSelectedItem(type);
        cbxCustType.setEnabled(false);
        cbxCustPriorityModel = new DefaultComboBoxModel(new String[] {"General","Family","VIP"});
        cbxCustPriority.setModel(cbxCustPriorityModel);
        Calendar currentTime  = Calendar.getInstance();
        SimpleDateFormat format = new SimpleDateFormat("yyyyMMddHHmmss");
        custCode =  format.format(currentTime.getTime());
    }

    public boolean CheckFormCustomser(){
        String txtEmailc = txtEmailC.getText().trim();
        String txtPhonec = txtPhoneC.getText().trim();
        String txtNamec = txtNameC.getText().trim();
        String Fax = txtFaxC.getText().trim();

        Pattern emailcheck = Pattern.compile(".+@.+\\.[a-z]+");
        Pattern phonecheck = Pattern.compile("[0-9]{9,11}");
        Pattern namecheck = Pattern.compile("^[a-zA-Z\\s]+");

        Matcher m = emailcheck.matcher(txtEmailc);
        Matcher p = phonecheck.matcher(txtPhonec);
        Matcher n = namecheck.matcher(txtNamec);
        Matcher f = namecheck.matcher(Fax);

        boolean email = m.matches();
        boolean phone = p.matches();
        boolean name = n.matches();
        boolean fax =  f.matches();

        if(txtNameC.getText().trim().equals("") || txtNameC.getText().trim().equals(null)){
            JOptionPane.showMessageDialog(this, "Name not null !!!"+"\n"+"Name can't contained number!","WARNING",JOptionPane.WARNING_MESSAGE);
            txtNameC.requestFocus();
            return false;
        }else if(name == false){
            JOptionPane.showMessageDialog(this, "Name is not valid !!!");
            txtNameC.requestFocus();
            return false;
        }
        if(txtEmailC.getText().trim().equals("")||txtEmailC.getText().trim().equals(null)){

        }else if(email == false){
           JOptionPane.showMessageDialog(this, "Email is not valid !!!"+"\n"+"Example : example@email.com","WARNING",JOptionPane.WARNING_MESSAGE);
           txtEmailC.requestFocus();
           return false;
        }
        if(cbxCustType.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(this, "Must select user type !!!");
            cbxCustType.requestFocus();
            return false;
        }
        if(cbxCustPriority.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(this, "Must select relationship !!!");
            cbxCustPriority.requestFocus();
            return false;
        }
        if(txtPhoneC.getText().trim().equals("")||txtPhoneC.getText().trim().equals(null)){
            JOptionPane.showMessageDialog(this, "You must enter the Phone: ");
            txtPhoneC.requestFocus();
            return false;
        }else if(phone == false){
            JOptionPane.showMessageDialog(this, "Not Invailid Phone !!!"+"\n"+"Phone can't contained text!"+"\n"+"Example : xxxxxxxxx or xxxxxxxxxxx","WARNING",JOptionPane.WARNING_MESSAGE);
            txtPhoneC.requestFocus();
            return false;
        }
        if(txtAddressC.getText().trim().equals("") || txtAddressC.getText().trim().equals(null)){
            JOptionPane.showMessageDialog(this, "Address not null !!!");
            txtAddressC.requestFocus();
            return false;
        }
        if(txtFaxC.getText().trim().equals("") || txtFaxC.getText().trim().equals(null)){
            
        }else if(fax==false){
            JOptionPane.showMessageDialog(this, "Not Invailid Fax !!!"+"\n"+"Fax can't contained text!"+"\n"+"Example : xxxxxxxxx or xxxxxxxxxxx","WARNING",JOptionPane.WARNING_MESSAGE);
            txtFaxC.requestFocus();
            return false;
        }

        return true;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * Dealers, Retailers and Distributors
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNameC = new javax.swing.JTextField();
        txtPhoneC = new javax.swing.JTextField();
        cbxCustType = new javax.swing.JComboBox();
        txtFaxC = new javax.swing.JTextField();
        txtEmailC = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddressC = new javax.swing.JTextArea();
        btnAdd = new javax.swing.JButton();
        cbxCustPriority = new javax.swing.JComboBox();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add new Custom");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Add Custom", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 51, 102))); // NOI18N

        jLabel1.setText("Name ");

        jLabel2.setText("Type ");

        jLabel3.setText("Phone ");

        jLabel4.setText("Fax ");

        jLabel5.setText("Email ");

        jLabel6.setText("Relationship ");

        jLabel7.setText("Address ");

        txtAddressC.setColumns(20);
        txtAddressC.setRows(5);
        jScrollPane1.setViewportView(txtAddressC);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/Add.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/exit.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFaxC)
                            .addComponent(txtNameC, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(txtPhoneC)
                            .addComponent(cbxCustType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmailC, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(cbxCustPriority, 0, 235, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClose)
                        .addGap(26, 26, 26))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(txtNameC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbxCustType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbxCustPriority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtPhoneC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtFaxC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if(CheckFormCustomser()){
            String name = txtNameC.getText().trim();
            String type = null;
            if(cbxCustType.getSelectedItem().toString().equals("Dealer")){
                type = "Dealer";
            }else if(cbxCustType.getSelectedItem().toString().equals("Retailer")){
                type = "Retailer";
            }else if(cbxCustType.getSelectedItem().toString().equals("Customer")){
                type = "Customer";
            }
            String priority = null;
            if(cbxCustPriority.getSelectedItem().toString().equals("General")){
                priority = "General";
            }else if(cbxCustPriority.getSelectedItem().toString().equals("Family")){
                priority = "Family";
            }else if(cbxCustPriority.getSelectedItem().toString().equals("VIP")){
                priority = "VIP";
            }

            String phone = txtPhoneC.getText().trim();
            String fax = txtFaxC.getText().trim();
            String email = txtEmailC.getText().trim();
            String address = txtAddressC.getText().trim();

            if(custMn.insertCustomer(this.custCode,name, type, phone, fax, email, address, priority)){
                JOptionPane.showMessageDialog(rootPane,"A Customer has been added successful");
                txtNameC.setText("");
                txtPhoneC.setText("");
                txtFaxC.setText("");
                txtEmailC.setText("");
                txtAddressC.setText("");
                cbxCustPriority.setSelectedIndex(0);
                cbxCustType.setSelectedIndex(0);
                this.dispose();

            }else{
                JOptionPane.showMessageDialog(this, "Cannot add new "+type+" to database", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_btnCloseActionPerformed

    /**
    * @param args the command line arguments
    */
    private String custCode;
    private CustomerManage custMn;
    private DefaultComboBoxModel cbxCustTypeModel;
    private DefaultComboBoxModel cbxCustPriorityModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JComboBox cbxCustPriority;
    private javax.swing.JComboBox cbxCustType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAddressC;
    private javax.swing.JTextField txtEmailC;
    private javax.swing.JTextField txtFaxC;
    private javax.swing.JTextField txtNameC;
    private javax.swing.JTextField txtPhoneC;
    // End of variables declaration//GEN-END:variables

}
