/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddOrderForm.java
 *
 * Created on Nov 9, 2009, 9:43:37 AM
 */

package GUI;

import java.sql.Date;
import Business.OrderManage;
import Business.OrderDetailsManage;
import Business.CustomerManage;
import Business.MedicineManage;
import Data.msbsOrders;
import Data.msbsOrderDetails;
import Data.msbsCustomer;
import Data.msbsMedicine;
import java.awt.Point;
import java.text.DecimalFormat;
import java.util.Calendar;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JDialog;
/**
 *
 * @author Administrator
 */
public class AddOrder_NewCustomForm extends javax.swing.JDialog {

    /** Creates new form AddOrderForm */
    public AddOrder_NewCustomForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        clicked=false;
        ordDeMn = new OrderDetailsManage();
        ordDetails = new msbsOrderDetails();
        ordMn = new OrderManage();
        orders = new msbsOrders();
        custMn = new CustomerManage();
        medMn = new MedicineManage();
        med = new msbsMedicine();
        allMedicine = new Vector<msbsMedicine>();
        orderCode = OrderModule.ordCode;
        Calendar currentTime  = Calendar.getInstance();
        SimpleDateFormat format = new SimpleDateFormat("yyyyMMddHHmmss");
        orderCode = "";
        txtTax.setText("0");
        txtDiscount.setText("0");
        orderCode +=  format.format(currentTime.getTime());
        newOrderDE = new Vector<msbsOrderDetails>();

        int userCode = Login.userLogged.getUserCode();
        TempCustList = custMn.getAllCustomer();
        String tempCusCode = TempCustList.elementAt(0).getCustomerCode();
        Date tempDate = new Date(System.currentTimeMillis());
        if(ordMn.getOrdersByOrderCode("0") == null){
            ordMn.insertOrder("0",tempCusCode,userCode,0,0.0,0.0,0,0,tempDate,"unknown",tempDate);
        }
        newOrderDE=ordDeMn.getAllOrderDetailsByOrderCode("0");
    }

     public boolean CheckFormCustomser(){
        String txtPhonec = txtPhone.getText().trim();
        String txtNamec = txtName.getText().trim();

        Pattern phonecheck = Pattern.compile("[0-9]{9,11}");
        Pattern namecheck = Pattern.compile("^[a-zA-Z\\s]+");

        Matcher p = phonecheck.matcher(txtPhonec);
        Matcher n = namecheck.matcher(txtNamec);

        boolean phone = p.matches();
        boolean name = n.matches();


        if(txtName.getText().trim().equals("") || txtName.getText().trim().equals(null)){
//            JOptionPane.showMessageDialog(this, "Name is not null!","WARNING",JOptionPane.WARNING_MESSAGE);
//            return false;
        }else if(name == false){
            JOptionPane.showMessageDialog(this, "Name can't containt number!");
            return false;
        }
        if(txtPhone.getText().trim().equals("") || txtPhone.getText().trim().equals(null)){

        }else if(phone == false){
            JOptionPane.showMessageDialog(this, "Invalid Phone number!"+"\n"+"Phone number containt 9-11 numbers","WARNING",JOptionPane.WARNING_MESSAGE);
            return false;
        }

        return true;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lbPhone = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSelectMedicine = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnDeleteAll = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTax = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCost = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Order");
        setAlwaysOnTop(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Customer Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 51, 102))); // NOI18N

        jLabel1.setText("Name");

        jLabel6.setText("Address");

        txtName.setToolTipText("Enter new Customer name");

        lbPhone.setText("Phone");

        txtAddress.setToolTipText("Customer's Address");

        txtPhone.setToolTipText("Customer's phone number");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(lbPhone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtAddress))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPhone)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Drugs list", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 51, 102))); // NOI18N

        tblSelectMedicine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Medicine", "Price", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblSelectMedicine.getTableHeader().setReorderingAllowed(false);
        tblSelectMedicine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblSelectMedicineMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblSelectMedicine);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/Add.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setToolTipText("Add medicine to drugs list");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/Delete.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setToolTipText("Delete medicine from drugs list");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnDeleteAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/Delete.png"))); // NOI18N
        btnDeleteAll.setText("Delete All");
        btnDeleteAll.setToolTipText("Delete medicine from drugs list");
        btnDeleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteAll))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnDelete)
                    .addComponent(btnDeleteAll))
                .addContainerGap())
        );

        btnCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/login.png"))); // NOI18N
        btnCreate.setText("Create");
        btnCreate.setToolTipText("Create new Order and insert it to database");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/exit.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setForeground(new java.awt.Color(240, 240, 240));

        jLabel2.setText("Tax");

        txtTax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTaxKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTaxKeyReleased(evt);
            }
        });

        jLabel3.setText("%");

        jLabel4.setText("Discount");

        txtDiscount.setEditable(false);

        jLabel9.setText("%");

        jLabel10.setText("Total");

        txtTotal.setEditable(false);

        jLabel12.setText("$");

        jLabel8.setText("Order Cost");

        txtCost.setEditable(false);

        jLabel11.setText("$");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addComponent(jLabel4))
                .addGap(79, 79, 79)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10))
                .addGap(10, 10, 10))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(326, Short.MAX_VALUE)
                .addComponent(btnCreate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClose)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnCreate))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        ordMn.deleteOrder("0");
        this.dispose();
}//GEN-LAST:event_btnCloseActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        clicked=true;
        if(txtTax.getText()==null || txtTax.getText().equals("")){
            txtTax.setText("0");
            CountTotal();
        }
        if(CheckFormCustomser()){
            String name;
            String phone;
            String address;
            String custCode="";
            if(txtName.getText()== null || txtName.getText().equals("")){
                name="unknown";
            }else{
                name=txtName.getText();
            }
            if(txtAddress.getText()== null || txtAddress.getText().equals("")){
                address="unknown";
            }else{
                address=txtAddress.getText();
            }
            if(txtPhone.getText()== null || txtPhone.getText().equals("")){
                phone="unknown";
            }else{
                phone=txtPhone.getText();
            }
            Calendar currentTime  = Calendar.getInstance();
            SimpleDateFormat format = new SimpleDateFormat("yyyyMMddHHmmss");
            custCode +=  format.format(currentTime.getTime());
            custMn.insertCustomer(custCode,name,"Customer",phone,"unknown","unknown",address,"General");
            Date current = new Date(System.currentTimeMillis());
            int tax = Integer.valueOf(txtTax.getText());
            int discount = Integer.valueOf(txtDiscount.getText());
            
            if(txtCost.getText() ==null||txtCost.getText().trim().equals("0.0")||txtCost.getText().trim().equals("")){
                JOptionPane.showMessageDialog(this,"There are any Medicine in this Order","WARNING",JOptionPane.WARNING_MESSAGE);
                return;
            }
            double total = Double.valueOf(txtTotal.getText());
            int userCode = Login.userLogged.getUserCode();
            if(ordMn.insertOrder(orderCode,custCode,userCode,2,total,total,tax,discount,current,address,current)){
                for(msbsOrderDetails od : newOrderDE){
                    ordDeMn.insertOrderDetails(od.getOrderCode(), od.getMedicineCode(), od.getPrice(), od.getQuantity());
                }
                ordMn.deleteOrder("0");
                JOptionPane.showMessageDialog(this,"Done!");
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this,"Failed!");
            }
        }
}//GEN-LAST:event_btnCreateActionPerformed

    public void CountTotal(){
        int quantity;
        double price;
        Cost=0;
        Total=0;
        int tax = Integer.valueOf(String.valueOf(txtTax.getText()));
        int discount = Integer.valueOf(String.valueOf(txtDiscount.getText()));
        for(int i = 0; i<newOrderDE.size(); i++){
            msbsOrderDetails temp = (msbsOrderDetails)newOrderDE.get(i);
            quantity = temp.getQuantity();
            price = temp.getPrice();
            Cost = Cost + (quantity*price);
        }
        Cost = Cost + (Cost*tax/100);
        Total = Cost - (Cost*discount/100) ;
        DecimalFormat df = new DecimalFormat(".#");
        txtTotal.setText(df.format(Total));
    }

    public void CountCost(){
        int quantity;
        double price;
        Cost=0;
        Total=0;
        for(int i = 0; i<newOrderDE.size(); i++){
            msbsOrderDetails temp = (msbsOrderDetails)newOrderDE.get(i);
            quantity = temp.getQuantity();
            price = temp.getPrice();
            Cost = Cost + (quantity*price);
        }
            txtCost.setText(String.valueOf(Cost));
    }


    public void AddMedicine(){
        newOrderDE = SelectMedicineForm.newOrderDETemp;
        ordDeMn.deleteOrderDetailByOrderCode("0");
        for(msbsOrderDetails od : newOrderDE){
            ordDeMn.insertOrderDetails("0", od.getMedicineCode(), od.getPrice(), od.getQuantity());
        }
    }
    public void refreshDrugList(){
        MedicineTableModel = new DefaultTableModel();
        MedicineTableModel.addColumn("Medicine");
        MedicineTableModel.addColumn("Price");
        MedicineTableModel.addColumn("Quantity");
        for(int i =0;i<newOrderDE.size();i++){
                msbsOrderDetails ode = (msbsOrderDetails)newOrderDE.get(i);
                msbsMedicine oldMed = medMn.getMedicineByCode(ode.getMedicineCode());
                Vector data = new Vector();
                data.add(oldMed.getMedicineName());
                data.add(ode.getPrice());
                data.add(ode.getQuantity());
                MedicineTableModel.addRow(data);

            }
            tblSelectMedicine.setModel(MedicineTableModel);
    }
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        SelectMedicineForm addNew;
        try {
            addNew = new SelectMedicineForm(this.frmParent, true,orderCode,newOrderDE);
            addNew.setLocationRelativeTo(this);
            addNew.setVisible(true);
            if(SelectMedicineForm.isDone==true){
                AddMedicine();
                refreshDrugList();
                CountCost();
                CountTotal();
            }else{
                newOrderDE = ordDeMn.getAllOrderDetailsByOrderCode("0");
            }

        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(AddOrderForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if(tblSelectMedicine.getSelectedRowCount()!=1){
            JOptionPane.showMessageDialog(this,"Please select One row one time!","Warning",2);
        }else{
            int index = tblSelectMedicine.getSelectedRow();
            int medCode = medMn.getCodeByName(String.valueOf(tblSelectMedicine.getValueAt(index, 0)));
            for(int i =0;i<newOrderDE.size();i++){
                if(medCode == ((msbsOrderDetails)newOrderDE.get(i)).getMedicineCode()){
                    newOrderDE.remove(i);
                }
            }
            ordDeMn.deleteOrderDetailByOrderCode("0");
            for(msbsOrderDetails od : newOrderDE){
                ordDeMn.insertOrderDetails("0", od.getMedicineCode(), od.getPrice(), od.getQuantity());
            }
            refreshDrugList();
            CountCost();
            CountTotal();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblSelectMedicineMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSelectMedicineMouseReleased
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            Point click = new Point(evt.getX(), evt.getY());
            int col = tblSelectMedicine.columnAtPoint(click);
            if(col != 2){
                tblSelectMedicine.removeEditor();
            }else{
                int row;
                row = tblSelectMedicine.rowAtPoint(click);
                tblSelectMedicine.editCellAt(row, 2);
                int mCode = medMn.getCodeByName(String.valueOf(tblSelectMedicine.getValueAt(row, 0)));
                SetQuantityForm setQ;
                setQ = new SetQuantityForm(this.frmParent, true,mCode);
                setQ.setLocationRelativeTo(this);
                setQ.setVisible(true);
                if(SetQuantityForm.isClick==true){
                    int newQuan = SetQuantityForm.newQuantity;
                    msbsOrderDetails temp = (msbsOrderDetails)newOrderDE.get(row);
                    temp.setQuantity(newQuan);
                    newOrderDE.set(row, temp);
                }
                refreshDrugList();
                CountCost();
            }
        }

    }//GEN-LAST:event_tblSelectMedicineMouseReleased

    private void txtTaxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTaxKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            CountTotal();
        }
    }//GEN-LAST:event_txtTaxKeyPressed

    private void btnDeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAllActionPerformed
        // TODO add your handling code here:
            newOrderDE.clear();
            ordDeMn.deleteOrderDetailByOrderCode("0");
            refreshDrugList();
            CountCost();
            CountTotal();
}//GEN-LAST:event_btnDeleteAllActionPerformed

    private void txtTaxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTaxKeyReleased
        // TODO add your handling code here:
        CountTotal();
    }//GEN-LAST:event_txtTaxKeyReleased

    /**
    * @param args the command line arguments
    */
    private String orderCode="";
    private double Cost=0;
    private double Total=0;
    private Vector allMedicine;
    private msbsOrders orders;
    private msbsOrderDetails ordDetails;
    private OrderManage ordMn;
    private OrderDetailsManage ordDeMn;
    private CustomerManage custMn;
    private msbsCustomer cust;
    private MedicineManage medMn;
    private msbsMedicine med;
    private JFrame frmParent;
    private JDialog dia;
    private DefaultTableModel MedicineTableModel;
    private Vector<msbsOrderDetails> newOrderDE ;
    private Vector<msbsCustomer> TempCustList;
    private String TempCode;
    static boolean clicked;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbPhone;
    static javax.swing.JTable tblSelectMedicine;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtTax;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

}
