/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddOrderForm.java
 *
 * Created on Nov 9, 2009, 9:43:37 AM
 */

package GUI;

import java.sql.Date;
import Business.OrderManage;
import Business.OrderDetailsManage;
import Business.CustomerManage;
import Business.MedicineManage;
import Data.msbsOrders;
import Data.msbsOrderDetails;
import Data.msbsCustomer;
import Data.msbsMedicine;
import java.awt.Point;
import java.text.DecimalFormat;
import java.util.Calendar;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
/**
 *
 * @author Administrator
 */
public class AddOrderForm extends javax.swing.JDialog {

    /** Creates new form AddOrderForm */
    public AddOrderForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        AOclicked=false;
        ordDeMn = new OrderDetailsManage();
        ordDetails = new msbsOrderDetails();
        ordMn = new OrderManage();
        orders = new msbsOrders();
        custMn = new CustomerManage();
        medMn = new MedicineManage();
        med = new msbsMedicine();
        allMedicine = new Vector<msbsMedicine>();
        orderCode = OrderModule.ordCode;
        TempCode = "0";
        Calendar currentTime  = Calendar.getInstance();
        SimpleDateFormat format = new SimpleDateFormat("yyyyMMddHHmmss");
        orderCode = "";
        txtTax.setText("0");
        txtDiscount.setText("0");
        orderCode +=  format.format(currentTime.getTime());
        newOrderDE = new Vector<msbsOrderDetails>();
        DateOrder.setDate(new Date(currentTime.getTime().getTime()));
        ExpiredDate.setDate(new Date(currentTime.getTime().getTime()));

        int userCode = Login.userLogged.getUserCode();
        TempCustList = custMn.getAllCustomer();
        String tempCusCode = TempCustList.elementAt(0).getCustomerCode();
        Date tempDate = new Date(System.currentTimeMillis());
        if(ordMn.getOrdersByOrderCode("0") == null){
            ordMn.insertOrder("0",tempCusCode,userCode,0,0.0,0.0,0,0,tempDate,"unknown",tempDate);
        }
        newOrderDE=ordDeMn.getAllOrderDetailsByOrderCode("0");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        DateOrder = new com.toedter.calendar.JDateChooser();
        ExpiredDate = new com.toedter.calendar.JDateChooser();
        btnSelectCustomer = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSelectMedicine = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnDeleteAll = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTax = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCost = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Customer Informations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 51, 102))); // NOI18N

        jLabel1.setText("Customer ");

        jLabel5.setText("Date Order ");

        jLabel6.setText("To Address");

        jLabel7.setText("Expired Time ");

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        DateOrder.setEnabled(false);

        ExpiredDate.setToolTipText("Time when this Order expired");

        btnSelectCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/up.png"))); // NOI18N
        btnSelectCustomer.setText("Select");
        btnSelectCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addComponent(btnSelectCustomer)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExpiredDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(DateOrder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(btnSelectCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(DateOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(ExpiredDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Drugs list", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 51, 102))); // NOI18N

        tblSelectMedicine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Medicine", "Price", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblSelectMedicine.getTableHeader().setReorderingAllowed(false);
        tblSelectMedicine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblSelectMedicineMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblSelectMedicine);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/Add.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setToolTipText("Add medicine to drugs list");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/Delete.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setToolTipText("Delete medicine from drugs list");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnDeleteAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/Delete.png"))); // NOI18N
        btnDeleteAll.setText("Delete All");
        btnDeleteAll.setToolTipText("Delete medicine from drugs list");
        btnDeleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd)
                .addGap(18, 18, 18)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteAll)
                .addContainerGap(432, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnDelete)
                    .addComponent(btnDeleteAll))
                .addContainerGap())
        );

        btnCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/login.png"))); // NOI18N
        btnCreate.setText("Create");
        btnCreate.setToolTipText("Create new Order and insert it to database");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/exit.png"))); // NOI18N
        btnCancel.setText("Close");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setForeground(new java.awt.Color(240, 240, 240));

        jLabel2.setText("Tax");

        txtTax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTaxKeyPressed(evt);
            }
        });

        jLabel3.setText("%");

        jLabel4.setText("Discount");

        txtDiscount.setEditable(false);

        jLabel9.setText("%");

        jLabel10.setText("Total");

        txtTotal.setEditable(false);

        jLabel12.setText("$");

        jLabel8.setText("Order Cost");

        txtCost.setEditable(false);

        jLabel11.setText("$");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addComponent(jLabel4))
                .addGap(79, 79, 79)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10))
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(520, Short.MAX_VALUE)
                .addComponent(btnCreate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel)
                .addGap(27, 27, 27))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnCancel))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        ordMn.deleteOrder("0");
        this.dispose();
}//GEN-LAST:event_btnCancelActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        AOclicked=true;
        String code = SelectCustomerForm.custCode;
        String address = txtAddress.getText();
        Date ordDate = new Date(DateOrder.getDate().getTime());
        Date expiredDate = new Date(ExpiredDate.getDate().getTime());
        int tax = Integer.valueOf(txtTax.getText());
        int discount = Integer.valueOf(txtDiscount.getText());
        if(txtCost.getText() ==null||txtCost.getText().trim().equals("0.0")||txtCost.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"There are any Medicine in this Order","WARNING",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(txtName.getText().trim() == null || txtName.getText().trim().equals("")||SelectCustomerForm.custCode==null){
            JOptionPane.showMessageDialog(this,"You must select a custom","WARNING",JOptionPane.WARNING_MESSAGE);
            return;
        }
        double total = Double.valueOf(txtTotal.getText());
        int userCode = Login.userLogged.getUserCode();
        if(ordMn.insertOrder(orderCode,code,userCode,0,total,0,tax,discount,ordDate,address,expiredDate)){
            for(msbsOrderDetails od : newOrderDE){
                ordDeMn.insertOrderDetails(od.getOrderCode(), od.getMedicineCode(), od.getPrice(), od.getQuantity());
            }
            JOptionPane.showMessageDialog(this,"Done!");
            ordDeMn.deleteOrderDetailByOrderCode("0");
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this,"Failed!");
            ordDeMn.deleteOrderDetailByOrderCode("0");
        }
}//GEN-LAST:event_btnCreateActionPerformed

    private void btnSelectCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectCustomerActionPerformed
        // TODO add your handling code here:
        SelectCustomerForm addNew;
        try {
            addNew = new SelectCustomerForm(this.frmparent, true);
            addNew.setLocationRelativeTo(this);
            addNew.setVisible(true);
            String code = SelectCustomerForm.custCode;
            cust = custMn.getCustomerByCode(code);
            txtName.setText(cust.getCustomerName());
            txtAddress.setText(cust.getCustomerAddress());
            String prio = cust.getCustomerPriority();
            if(prio.equals("General")){
                txtDiscount.setText("0");
            }else if(prio.equals("Family")){
                txtDiscount.setText("5");
            }else{
                txtDiscount.setText("10");
            }
            CountTotal();
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(AddOrderForm.class.getName()).log(Level.SEVERE, null, ex);
        }

}//GEN-LAST:event_btnSelectCustomerActionPerformed

    public void CountTotal(){
        int quantity;
        double price;
        Cost=0;
        Total=0;
        int tax = Integer.valueOf(String.valueOf(txtTax.getText()));
        int discount = Integer.valueOf(String.valueOf(txtDiscount.getText()));
        for(int i = 0; i<newOrderDE.size(); i++){
            msbsOrderDetails temp = (msbsOrderDetails)newOrderDE.get(i);
            quantity = temp.getQuantity();
            price = temp.getPrice();
            Cost = Cost + (quantity*price);
        }
        Cost = Cost + (Cost*tax/100);
        Total = Cost - (Cost*discount/100) ;
        DecimalFormat df = new DecimalFormat(".#");
        txtTotal.setText(df.format(Total));
    }

    public void CountCost(){
        int quantity;
        double price;
        Cost=0;
        Total=0;
        for(int i = 0; i<newOrderDE.size(); i++){
            msbsOrderDetails temp = (msbsOrderDetails)newOrderDE.get(i);
            quantity = temp.getQuantity();
            price = temp.getPrice();
            Cost = Cost + (quantity*price);
        }
            txtCost.setText(String.valueOf(Cost));
    }


    public void AddMedicine(){
        newOrderDE = SelectMedicineForm.newOrderDETemp;
        ordDeMn.deleteOrderDetailByOrderCode("0");
        for(msbsOrderDetails od : newOrderDE){
            ordDeMn.insertOrderDetails("0", od.getMedicineCode(), od.getPrice(), od.getQuantity());
        }
    }
    public void refreshDrugList(){
        MedicineTableModel = new DefaultTableModel();
        MedicineTableModel.addColumn("Medicine");
        MedicineTableModel.addColumn("Price");
        MedicineTableModel.addColumn("Quantity");
        for(int i =0;i<newOrderDE.size();i++){
                msbsOrderDetails ode = (msbsOrderDetails)newOrderDE.get(i);
                msbsMedicine oldMed = medMn.getMedicineByCode(ode.getMedicineCode());
                Vector data = new Vector();
                data.add(oldMed.getMedicineName());
                data.add(ode.getPrice());
                data.add(ode.getQuantity());
                MedicineTableModel.addRow(data);

            }
            tblSelectMedicine.setModel(MedicineTableModel);
    }
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        SelectMedicineForm addNew;
        try {
            addNew = new SelectMedicineForm(this.frmparent, true,orderCode,newOrderDE);
            addNew.setLocationRelativeTo(this);
            addNew.setVisible(true);
            if(SelectMedicineForm.isDone==true){
                AddMedicine();
                refreshDrugList();
                CountCost();
                CountTotal();
            }else{
                newOrderDE = ordDeMn.getAllOrderDetailsByOrderCode("0");
            }

        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(AddOrderForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if(tblSelectMedicine.getSelectedRowCount()!=1){
            JOptionPane.showMessageDialog(this,"Please select One row one time!","Warning",2);
        }else{
            int index = tblSelectMedicine.getSelectedRow();
            int medCode = medMn.getCodeByName(String.valueOf(tblSelectMedicine.getValueAt(index, 0)));
            for(int i =0;i<newOrderDE.size();i++){
                if(medCode == ((msbsOrderDetails)newOrderDE.get(i)).getMedicineCode()){
                    newOrderDE.remove(i);
                }
            }
            ordDeMn.deleteOrderDetailByOrderCode("0");
            for(msbsOrderDetails od : newOrderDE){
                ordDeMn.insertOrderDetails("0", od.getMedicineCode(), od.getPrice(), od.getQuantity());
            }
            refreshDrugList();
            CountCost();
            CountTotal();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblSelectMedicineMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSelectMedicineMouseReleased
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            Point click = new Point(evt.getX(), evt.getY());
            int col = tblSelectMedicine.columnAtPoint(click);
            if(col != 2){
                tblSelectMedicine.removeEditor();
            }else{
                int row;
                row = tblSelectMedicine.rowAtPoint(click);
                tblSelectMedicine.editCellAt(row, 2);
                int mCode = medMn.getCodeByName(String.valueOf(tblSelectMedicine.getValueAt(row, 0)));
                SetQuantityForm setQ;
                setQ = new SetQuantityForm(this.frmparent, true,mCode);
                setQ.setLocationRelativeTo(this);
                setQ.setVisible(true);
                if(SetQuantityForm.isClick==true){
                    int newQuan = SetQuantityForm.newQuantity;
                    msbsOrderDetails temp = (msbsOrderDetails)newOrderDE.get(row);
                    temp.setQuantity(newQuan);
                    newOrderDE.set(row, temp);
                }
                refreshDrugList();
                CountCost();
            }
        }

    }//GEN-LAST:event_tblSelectMedicineMouseReleased

    private void txtTaxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTaxKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            CountTotal();
        }
    }//GEN-LAST:event_txtTaxKeyPressed

    private void btnDeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAllActionPerformed
        // TODO add your handling code here:
            newOrderDE.clear();
            ordDeMn.deleteOrderDetailByOrderCode("0");
            refreshDrugList();
            CountCost();
            CountTotal();
}//GEN-LAST:event_btnDeleteAllActionPerformed

    /**
    * @param args the command line arguments
    */
    private String orderCode="";
    private double Cost=0;
    private double Total=0;
    private Vector allMedicine;
    private msbsOrders orders;
    private msbsOrderDetails ordDetails;
    private OrderManage ordMn;
    private OrderDetailsManage ordDeMn;
    private CustomerManage custMn;
    private msbsCustomer cust;
    private MedicineManage medMn;
    private msbsMedicine med;
    private JFrame frmparent;
    private DefaultTableModel MedicineTableModel;
    private Vector<msbsOrderDetails> newOrderDE ;
    static Vector<msbsOrderDetails> AddOrderDetailsList;
    private Vector<msbsCustomer> TempCustList;
    private String TempCode;
    static boolean AOclicked;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateOrder;
    private com.toedter.calendar.JDateChooser ExpiredDate;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteAll;
    private javax.swing.JButton btnSelectCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    static javax.swing.JTable tblSelectMedicine;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtTax;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

}
