/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ManagementForm.java
 *
 * Created on Nov 4, 2009, 4:23:33 PM
 */
package GUI;

import Business.UserManage;
import Data.msbsUser;
import java.text.SimpleDateFormat;

import java.util.Date;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import javax.swing.UnsupportedLookAndFeelException;

import java.awt.event.KeyEvent;
import javax.swing.KeyStroke;
import java.awt.event.ActionEvent;
import java.io.IOException;

/**
 *
 * @author Administrator
 */
public class Manager extends javax.swing.JFrame {

    /** Creates new form ManagementForm */
    UserModule userForm = new UserModule();

    public Manager() throws UnsupportedLookAndFeelException {
        initComponents();
        lbNameLogin.setText(Login.userLogged.getFullName());
        user = new msbsUser();
        
        mnSystem.setMnemonic('S');
        mnHelp.setMnemonic('H');
        miLogOut.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_L,ActionEvent.CTRL_MASK));
        miExit.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_X,ActionEvent.CTRL_MASK));
        miAbout.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_A,ActionEvent.CTRL_MASK));
        miHelp.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_H,ActionEvent.CTRL_MASK));
        
        Date todayD = new Date(System.currentTimeMillis());
        SimpleDateFormat dayFormat = new SimpleDateFormat("EEE, MMMM dd, yyyy");
        String todayS = dayFormat.format(todayD.getTime());
        lblSystemTime.setText(todayS);

    }

    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        HomePanel = new javax.swing.JPanel();
        reportPanel = new javax.swing.JPanel();
        providerManagement = new javax.swing.JPanel();
        medicineManagement = new javax.swing.JPanel();
        customerMamagement = new javax.swing.JPanel();
        userManagement = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbNameLogin = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblSystemTime = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnSystem = new javax.swing.JMenu();
        miLogOut = new javax.swing.JMenuItem();
        miExit = new javax.swing.JMenuItem();
        mnHelp = new javax.swing.JMenu();
        miHelp = new javax.swing.JMenuItem();
        miAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MANAGER - MSBS");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);

        jTabbedPane1.setForeground(new java.awt.Color(51, 51, 51));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        HomePanel = new HomeModule();

        jTabbedPane1.addTab("HOME     ", new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/home_icon.png")), HomePanel); // NOI18N

        javax.swing.GroupLayout reportPanelLayout = new javax.swing.GroupLayout(reportPanel);
        reportPanel.setLayout(reportPanelLayout);
        reportPanelLayout.setHorizontalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        reportPanelLayout.setVerticalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        reportPanel  = new ReportModule();

        jTabbedPane1.addTab("Report    ", new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/property_details_48.png")), reportPanel); // NOI18N

        javax.swing.GroupLayout providerManagementLayout = new javax.swing.GroupLayout(providerManagement);
        providerManagement.setLayout(providerManagementLayout);
        providerManagementLayout.setHorizontalGroup(
            providerManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        providerManagementLayout.setVerticalGroup(
            providerManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        try {
            providerManagement = new GUI.DistributorModule();
        } catch (UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }

        jTabbedPane1.addTab("Distributor", new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/distributoricon48.png")), providerManagement); // NOI18N

        javax.swing.GroupLayout medicineManagementLayout = new javax.swing.GroupLayout(medicineManagement);
        medicineManagement.setLayout(medicineManagementLayout);
        medicineManagementLayout.setHorizontalGroup(
            medicineManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        medicineManagementLayout.setVerticalGroup(
            medicineManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        try {
            medicineManagement = new GUI.MedicineModule(true);
        } catch (UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }

        jTabbedPane1.addTab("Medicine ", new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/pills5.png")), medicineManagement); // NOI18N

        javax.swing.GroupLayout customerMamagementLayout = new javax.swing.GroupLayout(customerMamagement);
        customerMamagement.setLayout(customerMamagementLayout);
        customerMamagementLayout.setHorizontalGroup(
            customerMamagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        customerMamagementLayout.setVerticalGroup(
            customerMamagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        try{
            customerMamagement = new GUI.CustomModule ();
        }catch(UnsupportedLookAndFeelException e){

        }

        jTabbedPane1.addTab("Custom ", new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/CustomerIcon.png")), customerMamagement); // NOI18N

        javax.swing.GroupLayout userManagementLayout = new javax.swing.GroupLayout(userManagement);
        userManagement.setLayout(userManagementLayout);
        userManagementLayout.setHorizontalGroup(
            userManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        userManagementLayout.setVerticalGroup(
            userManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        userManagement = new GUI.UserModule();

        jTabbedPane1.addTab("User        ", new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/UserIcon.png")), userManagement); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setBackground(new java.awt.Color(0, 0, 153));
        jLabel2.setFont(new java.awt.Font("Angsana New", 1, 24));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/welcome.png"))); // NOI18N

        lbNameLogin.setFont(new java.awt.Font("Monotype Corsiva", 1, 18));
        lbNameLogin.setForeground(new java.awt.Color(0, 51, 102));
        lbNameLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton1.setText("ChangePass");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblSystemTime.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblSystemTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSystemTime.setText("DD/MM/YYYY");
        lblSystemTime.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbNameLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
            .addComponent(lblSystemTime, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNameLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(9, 9, 9)
                .addComponent(lblSystemTime))
        );

        jLabel1.setBackground(new java.awt.Color(0, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/manager.png"))); // NOI18N

        mnSystem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/systemicon.png"))); // NOI18N
        mnSystem.setMnemonic('S');
        mnSystem.setText("System");
        mnSystem.setToolTipText("System Tool");
        mnSystem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSystemActionPerformed(evt);
            }
        });

        miLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/logout.png"))); // NOI18N
        miLogOut.setText("Log Off");
        miLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogOutActionPerformed(evt);
            }
        });
        mnSystem.add(miLogOut);

        miExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/exit.png"))); // NOI18N
        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        mnSystem.add(miExit);

        jMenuBar1.add(mnSystem);

        mnHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/help.png"))); // NOI18N
        mnHelp.setText("Help");
        mnHelp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        miHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/information.png"))); // NOI18N
        miHelp.setText("Help Topics");
        miHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miHelpActionPerformed(evt);
            }
        });
        mnHelp.add(miHelp);

        miAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/about.png"))); // NOI18N
        miAbout.setText("About Us");
        miAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAboutActionPerformed(evt);
            }
        });
        mnHelp.add(miAbout);

        jMenuBar1.add(mnHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 935, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        UserManage userMn = new UserManage();
        user = userMn.getUserByCode(userMn.getCodeByName(Login.userLogged.getNameLogin()));
        ChangePasswordForm chgPassForm = new ChangePasswordForm(this.frmParent, true, user);
        chgPassForm.setLocationRelativeTo(this);
        chgPassForm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void miLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogOutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login login = null;
        try {
            login = new Login();
            lbNameLogin.setText(Login.userLogged.getNameLogin());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
        }
        login.setVisible(true);
}//GEN-LAST:event_miLogOutActionPerformed

    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Do you want to exit?");
        if(result == JOptionPane.YES_OPTION){
            System.exit(0);
        }
}//GEN-LAST:event_miExitActionPerformed

    private void mnSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSystemActionPerformed

}//GEN-LAST:event_mnSystemActionPerformed

    private void miHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miHelpActionPerformed
        // TODO add your handling code here:
        Runtime rt = Runtime.getRuntime();
        try {
            String filePath = "msbsUserGuide.chm";
            rt.exec("hh.exe "+filePath);
            
        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,"Cannot load help file!","Error",JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_miHelpActionPerformed

    private void miAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAboutActionPerformed
        // TODO add your handling code here:
        AboutUsForm ab = new AboutUsForm(this.frmParent,true);
        ab.setLocationRelativeTo(this);
        ab.setVisible(true);
}//GEN-LAST:event_miAboutActionPerformed
    /**
     * @param args the command line arguments
     */
 
    private msbsUser user;
    private JFrame frmParent;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HomePanel;
    private javax.swing.JPanel customerMamagement;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbNameLogin;
    private javax.swing.JLabel lblSystemTime;
    private javax.swing.JPanel medicineManagement;
    private javax.swing.JMenuItem miAbout;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miHelp;
    private javax.swing.JMenuItem miLogOut;
    private javax.swing.JMenu mnHelp;
    private javax.swing.JMenu mnSystem;
    private javax.swing.JPanel providerManagement;
    private javax.swing.JPanel reportPanel;
    private javax.swing.JPanel userManagement;
    // End of variables declaration//GEN-END:variables
}
