/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PurchaseModule.java
 *
 * Created on Nov 13, 2009, 2:07:11 PM
 */
package GUI;

import Business.OrderManage;
import Business.OrderDetailsManage;
import Business.CustomerManage;
import Business.UserManage;
import Data.msbsOrders;
import Data.msbsOrderDetails;
import Data.msbsCustomer;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Administrator
 */
public class PurchaseModule extends javax.swing.JPanel {

    /** Creates new form PurchaseModule */
    public PurchaseModule() {
        initComponents();
        OrdMn = new OrderManage();
        CustMn = new CustomerManage();
        Orders = new msbsOrders();
        tableColumn = new TableColumn();
        getAllOrder();
    }

    public void getAllOrder() {
        allOrders = OrdMn.getOrdersByStatus(2);
        purchaseTabelModel = new DefaultTableModel();
        purchaseTabelModel.addColumn("Order Code");
        purchaseTabelModel.addColumn("Customer");
        purchaseTabelModel.addColumn("Seller");
        purchaseTabelModel.addColumn("Date Order");
        purchaseTabelModel.addColumn("Delivered Date");
        purchaseTabelModel.addColumn("Total Payoff");
        String name;
        String type;
        if (txtCustNameFilter.getText().equals(null) || txtCustNameFilter.getText().equals("")) {
            name = "";
        } else {
            name = txtCustNameFilter.getText().trim().toLowerCase();
        }
        type = String.valueOf(cbxCustTypeFilter.getSelectedItem());
        if (cbxCustTypeFilter.getSelectedIndex() == 0) {
            type = "";
        }
        for (int i = 0; i < allOrders.size(); i++) {
            Orders = (msbsOrders) allOrders.get(i);
            if ((CustMn.getCustomerByCode(Orders.getCustomerCode()).getCustomerName()).toLowerCase().matches(".*" + name.toLowerCase() + ".*") && (CustMn.getCustomerByCode(Orders.getCustomerCode()).getCustomerType()).toLowerCase().matches(".*" + type.toLowerCase() + ".*")) {
                Vector newData = new Vector();
                String ordCode = String.valueOf(Orders.getOrderCode());
                newData.add(ordCode);
                String CustName;
                CustName = CustMn.getCustomerByCode(Orders.getCustomerCode()).getCustomerName();
                newData.add(CustName);
                newData.add(new UserManage().getUserByCode(Orders.getUserCode()).getFullName());
                newData.add(Orders.getOrderDate());
                newData.add(Orders.getExpiredTime());
                newData.add((float) Orders.getTotal());
                purchaseTabelModel.addRow(newData);
            }

        }
        tblPurchasal.setModel(purchaseTabelModel);
        tableColumn = tblPurchasal.getColumnModel().getColumn(0);
        tableColumn.setPreferredWidth(0);
        tableColumn.setMinWidth(0);
        tableColumn.setMaxWidth(0);
        lblTotalBills.setText(String.valueOf(tblPurchasal.getRowCount()));
    }

    public msbsOrders getCodeSelectedRow() {
        int index = tblPurchasal.getSelectedRow();
        String OrdCode = String.valueOf(tblPurchasal.getValueAt(index, 0));
        Orders = OrdMn.getOrdersByOrderCode(OrdCode);
        if (Orders != null) {
            return Orders;
        }
        return null;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        txtCustNameFilter = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbxCustTypeFilter = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPurchasal = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        lblTotalBills = new javax.swing.JLabel();
        tbnCompDetails = new javax.swing.JButton();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filter by customer and type", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 51, 102))); // NOI18N

        txtCustNameFilter.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtCustNameFilterCaretUpdate(evt);
            }
        });

        jLabel3.setText("Name: ");

        jLabel4.setText("Type:");

        cbxCustTypeFilter.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All Type", "Customer", "Dealer", "Retailer" }));
        cbxCustTypeFilter.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCustTypeFilterItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(32, 32, 32)
                .addComponent(txtCustNameFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(cbxCustTypeFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(txtCustNameFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel4)
                .addComponent(cbxCustTypeFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Completed Bills List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 51, 102))); // NOI18N

        tblPurchasal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer", "Seller", "Order Date", "Delivered Date", "Total Payoff"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPurchasal.getTableHeader().setReorderingAllowed(false);
        tblPurchasal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblPurchasalMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblPurchasal);

        jLabel5.setText("Total Bills: ");

        tbnCompDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/edit.png"))); // NOI18N
        tbnCompDetails.setText("Bills Details");
        tbnCompDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnCompDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalBills, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 582, Short.MAX_VALUE)
                .addComponent(tbnCompDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblTotalBills, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbnCompDetails)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustNameFilterCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtCustNameFilterCaretUpdate
        // TODO add your handling code here:
        getAllOrder();
}//GEN-LAST:event_txtCustNameFilterCaretUpdate

    private void cbxCustTypeFilterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCustTypeFilterItemStateChanged
        // TODO add your handling code here:
        getAllOrder();
}//GEN-LAST:event_cbxCustTypeFilterItemStateChanged

    private void tblPurchasalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPurchasalMousePressed
        //TODO add your handling code here:
        if (evt.getClickCount() != 1) {
            tblPurchasal.removeEditor();
            ViewOrderDetailForm tardyDetails = new ViewOrderDetailForm(frmParent, true, OrdMn.getOrdersByOrderCode(String.valueOf(tblPurchasal.getValueAt(tblPurchasal.getSelectedRow(), 0))), "");
            tardyDetails.setLocationRelativeTo(this);
            tardyDetails.setVisible(true);

        }
}//GEN-LAST:event_tblPurchasalMousePressed

    private void tbnCompDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnCompDetailsActionPerformed
        // TODO add your handling code here:
        if (tblPurchasal.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Select a bill in Bills List to view details! ");
        } else if (tblPurchasal.getSelectedRowCount() > 1) {
            JOptionPane.showMessageDialog(this, "Do not select more one bill !");
        } else {
            ViewOrderDetailForm tardyDetails = new ViewOrderDetailForm(frmParent, true, OrdMn.getOrdersByOrderCode(String.valueOf(tblPurchasal.getValueAt(tblPurchasal.getSelectedRow(), 0))), "");
            tardyDetails.setLocationRelativeTo(this);
            tardyDetails.setVisible(true);
        }
}//GEN-LAST:event_tbnCompDetailsActionPerformed
    private msbsOrders Orders;
    private OrderManage OrdMn;
    private OrderDetailsManage OrdDeMn;
    private CustomerManage CustMn;
    private msbsCustomer cust;
    private Vector<msbsOrders> allOrders;
    private JFrame frmParent;
    private DefaultTableModel purchaseTabelModel;
    private TableColumn tableColumn;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbxCustTypeFilter;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalBills;
    private javax.swing.JTable tblPurchasal;
    private javax.swing.JButton tbnCompDetails;
    private javax.swing.JTextField txtCustNameFilter;
    // End of variables declaration//GEN-END:variables
}
