/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SetPayForm.java
 *
 * Created on Nov 15, 2009, 4:58:22 PM
 */

package GUI;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author V-sign
 */
public class SetPayForm extends javax.swing.JDialog {

    /** Creates new form SetPayForm */
    public SetPayForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        isFull=false;
        fla=false;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMoney = new javax.swing.JTextField();
        btnSet = new javax.swing.JButton();
        btnFull = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Total Payed");

        btnSet.setText("Set");
        btnSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetActionPerformed(evt);
            }
        });

        btnFull.setText("Pay Full");
        btnFull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFullActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFull))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFull)
                    .addComponent(btnSet))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetActionPerformed
        // TODO add your handling code here:
        double temp = Double.valueOf(String.valueOf(txtMoney.getText()));
        double currentMoney = ViewOrderDetailForm.oldMoney;
        if(temp > ViewOrderDetailForm.allCost){
            JOptionPane.showMessageDialog(frmParent,"Your money is over than Total cost!");
            txtMoney.requestFocus();
            txtMoney.selectAll();
        }else{
            fla =true;
            money = temp;
            this.dispose();
        }
}//GEN-LAST:event_btnSetActionPerformed

    private void btnFullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFullActionPerformed
        // TODO add your handling code here:
        fla=true;
        isFull=true;
        money = ViewOrderDetailForm.allCost;
        this.dispose();
    }//GEN-LAST:event_btnFullActionPerformed

    /**
    * @param args the command line arguments
    */
    static boolean isFull;
    static boolean fla;
    static double money;
    private JFrame frmParent;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFull;
    private javax.swing.JButton btnSet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtMoney;
    // End of variables declaration//GEN-END:variables

}
