/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SetQuantityForm.java
 *
 * Created on Nov 14, 2009, 12:12:36 PM
 */

package GUI;

import Business.MedicineManage;
import Data.msbsMedicine;
import javax.swing.JOptionPane;

/**
 *
 * @author V-sign
 */
public class SetQuantityForm extends javax.swing.JDialog {

    /** Creates new form SetQuantityForm */
    public SetQuantityForm(java.awt.Frame parent, boolean modal,int code) {
        super(parent, modal);
        initComponents();
        medMn = new MedicineManage();
        med = new msbsMedicine();
        quantity = medMn.getMedicineByCode(code).getAvailableAmount();
        isClick=false;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        btnSet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("");
        setAlwaysOnTop(true);

        jLabel1.setText("Quantity");

        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantityKeyPressed(evt);
            }
        });

        btnSet.setText("Set");
        btnSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnSet)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void SetQuantity(){ 
        int getQuan = Integer.valueOf(txtQuantity.getText());
        if(quantity < getQuan){
            JOptionPane.showMessageDialog(this,"Our's warehouse has only "+quantity+" of this medicine avaiable!");
            txtQuantity.setText(String.valueOf(quantity));
            txtQuantity.requestFocus();
            txtQuantity.selectAll();
        }else if(quantity==getQuan){
            isClick=true;
            newQuantity = getQuan;
            this.dispose();
        }else{
            isClick=true;
            newQuantity = getQuan;
            this.dispose();
        }
    }
    private void btnSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetActionPerformed
        // TODO add your handling code here:
        SetQuantity();
    }//GEN-LAST:event_btnSetActionPerformed

    private void txtQuantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            SetQuantity();
        }
    }//GEN-LAST:event_txtQuantityKeyPressed

    /**
    * @param args the command line arguments
    */
   
    private MedicineManage medMn;
    private msbsMedicine med;
    private int quantity;
    static boolean isClick;
    static int newQuantity;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables

}
