/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UpdateDistributorForm.java
 *
 * Created on Nov 8, 2009, 4:31:11 PM
 */
package GUI;

import Business.SupplierManage;
import Data.msbsSupplier;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class UpdateDistributorForm extends javax.swing.JDialog {

    /** Creates new form UpdateDistributorForm */
    public UpdateDistributorForm(java.awt.Frame parent, boolean modal, msbsSupplier editSup) {
        super(parent, modal);
        initComponents();
        tempSup = new msbsSupplier();
        this.tempSup = editSup;
        supMn = new SupplierManage();

        txtName.setText(tempSup.getSupplierName());
        txtFullName.setText(tempSup.getSupplierFullName());
        txtAddress.setText(tempSup.getSupplierAddress());
        txtPhone.setText(tempSup.getSupplierPhone());
        txtFax.setText(tempSup.getSupplierFax());
        txtEmail.setText(tempSup.getSupplierEmail());
        txtWebsite.setText(tempSup.getSupplierWebsite());
        if (modal == false) {
            txtName.setEditable(false);
            txtFullName.setEditable(false);
            txtAddress.setEditable(false);
            txtFax.setEditable(false);
            txtEmail.setEditable(false);
            txtWebsite.setEditable(false);
            txtAddress.setEditable(false);
            txtPhone.setEditable(false);
            btUpdate.setVisible(false);
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    public boolean checkProvider() {
        String txtEmailp = txtEmail.getText().trim();
        String txtPhonep = txtPhone.getText().trim();
        String txtNamep = txtFullName.getText().trim();
        String txtname = txtName.getText().trim();
        String Fax = txtFax.getText().trim();
        Pattern emailcheck = Pattern.compile(".+@.+\\.[a-z]+");
        Pattern phonecheck = Pattern.compile("[0-9]{9,11}");
        Pattern namecheck = Pattern.compile("^[a-zA-Z\\s]+");
        Pattern namecheck1 = Pattern.compile("^[a-zA-Z\\s]+");
        Pattern fax = Pattern.compile("[0-9]{9,11}");
        Matcher m = emailcheck.matcher(txtEmailp);
        Matcher p = phonecheck.matcher(txtPhonep);
        Matcher n = namecheck.matcher(txtNamep);
        Matcher n1 = namecheck1.matcher(txtname);
        Matcher faxC = fax.matcher(Fax);
        boolean email = m.matches();
        boolean phone = p.matches();
        boolean name = n.matches();
        boolean name1 = n1.matches();
        boolean faxCheck = faxC.matches();

        if (txtName.getText().trim().equals("") || txtName.getText().trim().equals(null)) {
            JOptionPane.showMessageDialog(this, "Name is not null !!!");
            txtName.requestFocus();
            return false;
        } else if (name1 == false) {
            JOptionPane.showMessageDialog(this, "Name is not valid !!!" + "\n" + "Name can't contained number!", "WARNING", JOptionPane.WARNING_MESSAGE);
            txtName.requestFocus();
            return false;

        }
        if (txtFullName.getText().trim().equals("") || txtFullName.getText().trim().equals(null)) {
            JOptionPane.showMessageDialog(this, "FullName is not null !!!");
            txtFullName.requestFocus();
            return false;
        } else if (name == false) {
            JOptionPane.showMessageDialog(this, "FullName is not valid !!!" + "\n" + "FullName can't contained number!", "WARNING", JOptionPane.WARNING_MESSAGE);
            txtFullName.requestFocus();
            return false;

        }
        if (txtPhone.getText().equals("") || txtPhone.getText().equals(null)) {
            JOptionPane.showMessageDialog(this, "Phone is not null !!!");
            txtPhone.requestFocus();
            return false;
        } else if (phone == false) {
            JOptionPane.showMessageDialog(this, "Phone is not valid !!!" + "\n" + "Phone can't contained text" + "\n" + "example : xxxxxxxxx or xxxxxxxxxxx", "WRANING", JOptionPane.WARNING_MESSAGE);
            txtPhone.requestFocus();
            return false;

        }
        if (txtAddress.getText().trim().equals("") || txtAddress.getText().trim().equals(null)) {
            txtAddress.requestFocus();
            JOptionPane.showMessageDialog(this, "Address is not null !!!");
            return false;
        }
        if (txtFax.getText().trim().equals("") || txtFax.getText().trim().equals(null)) {
        } else if (faxCheck == false) {
            JOptionPane.showMessageDialog(this, "Fax is not valid !!!" + "\n" + "Fax can't contained text" + "\n" + "example : xxxxxxxxx or xxxxxxxxxxx", "WRANING", JOptionPane.WARNING_MESSAGE);
            txtFax.requestFocus();
            return false;
        }

        if (txtEmail.getText().trim().equals("") || txtEmail.getText().trim().equals(null)) {
        } else if (email == false) {
            JOptionPane.showMessageDialog(this, "Email is not valid !!!" + "\n" + "Example : example@email.com", "WRANING", JOptionPane.WARNING_MESSAGE);
            txtEmail.requestFocus();
            return false;
        }
        return true;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtFullName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtFax = new javax.swing.JTextField();
        txtWebsite = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        btUpdate = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update Distributor Infomation");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Distributor Update", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 51, 102))); // NOI18N

        jLabel1.setText("Name ");

        jLabel2.setText("Full Name  ");

        jLabel3.setText("Address ");

        jLabel4.setText("Email  ");

        jLabel5.setText("Fax  ");

        jLabel6.setText("Phone ");

        jLabel7.setText("Website ");

        txtFax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaxActionPerformed(evt);
            }
        });

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        btUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/Update.png"))); // NOI18N
        btUpdate.setText("Update");
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/distributoricon.png"))); // NOI18N

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/exit.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnClose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFax)
                            .addComponent(txtPhone)
                            .addComponent(txtFullName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addComponent(txtEmail)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(txtWebsite))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaxActionPerformed

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        // TODO add your handling code here:

        String name = txtName.getText().trim();
        String fullName = txtFullName.getText().trim();
        String Address = txtAddress.getText().trim();
        String Phone = txtPhone.getText().trim();
        String Fax = txtFax.getText().trim();
        String Email = txtEmail.getText().trim();
        String website = txtWebsite.getText();
        int code = tempSup.getSupplierCode();
        if (checkProvider()) {
            if (supMn.updateSupplier(code, name, fullName, Address, Phone, Fax, Email, website)) {
                JOptionPane.showMessageDialog(rootPane, "Update Successfull! ");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Check your data input!", "UPDATE FAILED", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btUpdateActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_btnCloseActionPerformed
    /**
     * @param args the command line arguments
     */
    private SupplierManage supMn;
    private msbsSupplier tempSup;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btUpdate;
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtWebsite;
    // End of variables declaration//GEN-END:variables
}
