/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserModule.java
 *
 * Created on Nov 4, 2009, 4:30:13 PM
 */
package GUI;

import Data.msbsUser;
import Business.UserManage;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Administrator
 */
public class UserModule extends javax.swing.JPanel {

    /** Creates new form UserModule */
    private msbsUser user = null;
    private UserManage userMn = null;
    private Vector<msbsUser> allUser = null;
    private int totalUser;

    public UserModule() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        } catch (IllegalAccessException ex) {
            ex.printStackTrace();
        } catch (InstantiationException ex) {
            ex.printStackTrace();
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        }
        initComponents();
        tableColumnl = new TableColumn();
        user = new msbsUser();
        userMn = new UserManage();
        allUser = new Vector<msbsUser>();
        getUser();


    }

    public msbsUser getCodeSelectedRow() {
        int index = tblUsermanager.getSelectedRow();
        int userCode = (int) Integer.valueOf(String.valueOf(tblUsermanager.getValueAt(index, 0)));
        user = userMn.getUserByCode(userCode);
        if (user != null) {
            return user;
        }
        return null;
    }

    public void getUser() {
        String uName;
        String uType;
        allUser = new Vector<msbsUser>();
        allUser = userMn.getAllUser();

        if (txtNameFilter.getText().trim().equals(null) || txtNameFilter.getText().trim().equals("")) {
            uName = "";
        } else {
            uName = txtNameFilter.getText().trim().toLowerCase();
        }
        if (cbxUserType.getSelectedIndex() == 0) {
            uType = "";
        } else if (cbxUserType.getSelectedIndex() == 1) {
            uType = "Manager";
        } else if (cbxUserType.getSelectedIndex() == 2) {
            uType = "Seller";
        } else {
            uType = "Accountant";
        }
        model = new DefaultTableModel();
        model.addColumn("Code");
        model.addColumn("Name Login");
        model.addColumn("Full Name");
        model.addColumn("Type");
        model.addColumn("Phone");
        model.addColumn("Address");
        model.addColumn("Email");
        model.addColumn("Active");
        totalUser = 0;

        for (int i = 0; i < allUser.size(); i++) {
            user = (msbsUser) allUser.get(i);
            Vector newData = new Vector();
            if (user.getFullName().toLowerCase().matches(".*" + uName.toLowerCase() + ".*") && userMn.getUserTypeName(user.getUserTypeCode()).toLowerCase().matches(".*" + uType.toLowerCase() + ".*")) {
                newData.addElement(user.getUserCode());
                newData.addElement(user.getNameLogin());
                newData.addElement(user.getFullName());
                newData.addElement(userMn.getUserTypeName(user.getUserTypeCode()));
                newData.addElement(user.getUserPhone());
                newData.addElement(user.getUserAddress());
                newData.addElement(user.getUserEmail());
                newData.addElement(user.getUserActive());
                model.addRow(newData);
                totalUser++;
            }


        }
        tblUsermanager.setModel(model);
        tableColumnl = tblUsermanager.getColumnModel().getColumn(0);
        tableColumnl.setPreferredWidth(0);
        tableColumnl.setMinWidth(0);
        tableColumnl.setMaxWidth(0);
        lblTotalUser.setText(String.valueOf(totalUser));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btAdd = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTotalUser = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNameFilter = new javax.swing.JTextField();
        cbxUserType = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsermanager = new javax.swing.JTable();

        btAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/Add.png"))); // NOI18N
        btAdd.setText("Add");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/Delete.png"))); // NOI18N
        btDelete.setText("Delete");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        btEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icon/Update.png"))); // NOI18N
        btEdit.setText("View Details");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });

        jLabel1.setText("Total User: ");

        lblTotalUser.setText("0");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filter User", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 51, 102))); // NOI18N

        jLabel2.setText("Filter by Name: ");

        txtNameFilter.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtNameFilterCaretUpdate(evt);
            }
        });

        cbxUserType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select.....", "Manager", "Seller", "Accountant" }));
        cbxUserType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxUserTypeItemStateChanged(evt);
            }
        });

        jLabel3.setText("Type:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtNameFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbxUserType, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(txtNameFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cbxUserType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "USER LIST", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 51, 102))); // NOI18N

        tblUsermanager.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        tblUsermanager.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name Login", "Full Name ", "User Type", "Address ", "Phone  ", "Email ", "Active "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblUsermanager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsermanagerMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblUsermanagerMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsermanager);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 435, Short.MAX_VALUE)
                .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btAdd)
                        .addComponent(btEdit)
                        .addComponent(btDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(lblTotalUser)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // TODO add your handling code here:
        AddUserForm addNew = new AddUserForm(this.frmParent, true);
        addNew.setLocationRelativeTo(this);
        addNew.setVisible(true);
        getUser();
    }//GEN-LAST:event_btAddActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        // TODO add your handling code here:
        if (tblUsermanager.getSelectedRowCount() == 1) {
            UpdateUserForm updateUser = new UpdateUserForm(this.frmParent, true, getCodeSelectedRow());
            updateUser.setLocationRelativeTo(this);
            updateUser.setVisible(true);
            getUser();
        } else if (tblUsermanager.getSelectedRowCount() > 1) {
            JOptionPane.showMessageDialog(this, "Do not select more one User", "WARNING", JOptionPane.WARNING_MESSAGE);
        } else if (tblUsermanager.getSelectedRowCount() > 1) {
            JOptionPane.showMessageDialog(this, "Do not select more one User", "WARNING", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Please Select a User", "WARNING", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btEditActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        // TODO add your handling code here:
        msbsUser tempUser = new msbsUser();

        if (tblUsermanager.getSelectedRowCount() == 1) {
            tempUser = getCodeSelectedRow();
            int result;
            if (Login.userLogged.getUserCode() != tempUser.getUserCode()) {
                result = JOptionPane.showConfirmDialog(frmParent, "Are you sure delete this User? ");
                if (result == JOptionPane.YES_OPTION) {
                    if (userMn.deleteUser(tempUser.getUserCode())) {
                        JOptionPane.showMessageDialog(frmParent, "Delete successfull! ");
                    }else{
                        JOptionPane.showMessageDialog(this, "Cannot Delete this User !", "DELETE FAILED", JOptionPane.ERROR_MESSAGE);
                    }
                    getUser();
                } else if (result == JOptionPane.NO_OPTION) {
                    getUser();
                }
            } else {
                JOptionPane.showMessageDialog(this, "This user is logging", "WARNING", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Do not select more than one User", "WARNING", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btDeleteActionPerformed

    private void tblUsermanagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsermanagerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblUsermanagerMouseClicked

    private void tblUsermanagerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsermanagerMousePressed
        // TODO add your handling code here:
        tblUsermanager.removeEditor();
        if (evt.getClickCount() == 2) {
            UpdateUserForm updateUser = new UpdateUserForm(this.frmParent, true, getCodeSelectedRow());
            updateUser.setLocationRelativeTo(this);
            updateUser.setVisible(true);
            getUser();
        }
    }//GEN-LAST:event_tblUsermanagerMousePressed

    private void txtNameFilterCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtNameFilterCaretUpdate
        // TODO add your handling code here:
        getUser();
    }//GEN-LAST:event_txtNameFilterCaretUpdate

    private void cbxUserTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxUserTypeItemStateChanged
        // TODO add your handling code here:
        getUser();
    }//GEN-LAST:event_cbxUserTypeItemStateChanged
    private TableColumn tableColumnl;
    private DefaultTableModel model;
    private JFrame frmParent;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btEdit;
    private javax.swing.JComboBox cbxUserType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalUser;
    private javax.swing.JTable tblUsermanager;
    private javax.swing.JTextField txtNameFilter;
    // End of variables declaration//GEN-END:variables
}
